# Gradle
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true
org.gradle.daemon = false
fabric.loom.ignoreDependencyLoomVersionValidation = true
fabric.loom.allowMismatchedPlatformVersions = true
fabric.loom.multiProjectOptimisation = false

# Project
mod_id = a_good_place
mod_name = A Good Place
mod_version = 26.1.2-1.3.5
mod_author = MehVahdJukaar
mod_description = Funni block placement animations
mod_license = MIT
mod_authors = MehVahdJukaar, Enjarai
mod_homepage = https://www.curseforge.com/minecraft/mc-mods/a_good_place
mod_credits = MehVahdJukaar, Enjarai
mod_github = https://github.com/MehVahdJukaar/a_good_place

release_type = release
maven_group = net.mehvahdjukaar

# Publishing
repository = MehVahdJukaar/a_good_place
modrinth_project_id = a-good-place
curseforge_project_id = 1020455

# MC / loader versions
mc_version = 26.1.2

neoforge_version = 26.1.2.71

fabric_api_version = 0.150.0+26.1.2
fabric_loader_version = 0.19.2



